version: '3'
services:
  test:
    image: rpctropic/tropicrpc-prod
    container_name: tropicrpc-test
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  node_modules:
